-- CREATE EVENT TABLE
CREATE TABLE IF NOT EXISTS EVENT
(
EVENT_ID IDENTITY PRIMARY KEY NOT NULL,
EVENT_NAME VARCHAR(255) NOT NULL,
HOST_FIRST_NAME VARCHAR(255) NOT NULL,
HOST_LAST_NAME VARCHAR(255) NOT NULL,
LOCATION VARCHAR(255) NOT NULL,
EVENT_DATE TIMESTAMP NOT NULL,
EVENT_MESSAGE VARCHAR(1000) NOT NULL,
EVENT_STATUS INT DEFAULT 0 NOT NULL,
DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
/**
--- ENTER SAMPLE EVENTS
INSERT INTO EVENT(EVENT_NAME,HOST_FIRST_NAME, HOST_LAST_NAME, LOCATION, EVENT_DATE, EVENT_MESSAGE) 
VALUES('BIRTHDAY PARTY','JOHN','SMITH','CMR',PARSEDATETIME('Sat, 3 Feb 2018 05:30:00 PDT',
    'EEE, d MMM yyyy HH:mm:ss z', 'en', 'PDT'), 'PLEASE ATTEND WITH YOUR FAMILY');
    
INSERT INTO EVENT(EVENT_NAME,HOST_FIRST_NAME, HOST_LAST_NAME, LOCATION,EVENT_DATE, EVENT_MESSAGE) 
VALUES('BIRTHDAY PARTY','JOHN','SMITH','CMR',PARSEDATETIME ('31-05-13 11:34:24','dd-MM-yy hh:mm:ss'), 'PLEASE BRING GIFTS');   
**/
-- CREATE INVITATION TABLE FOR AN EVENT
CREATE TABLE IF NOT EXISTS INVITATION
(
INVITATION_ID IDENTITY PRIMARY KEY NOT NULL,
EVENT_ID VARCHAR(255) NOT NULL,
RECIPIENT_FIRST_NAME VARCHAR(255) NOT NULL,
RECIPIENT_LAST_NAME VARCHAR(255) NOT NULL,
RECIPIENT_EMAIL VARCHAR(255) NOT NULL,
RESPONSE_DATE TIMESTAMP,
RESPONSE_MESSAGE VARCHAR(1000),
INVITATION_STATUS INT DEFAULT 0 NOT NULL,
DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
/**
INSERT INTO INVITATION(EVENT_ID, RECIPIENT_FIRST_NAME, RECIPIENT_LAST_NAME, RECIPIENT_EMAIL, RESPONSE_DATE, RESPONSE_MESSAGE, INVITATION_STATUS) 
VALUES(1,'MIKE','KAHN','MIKE@SHSH.COM',PARSEDATETIME ('31-05-13 11:34:24','dd-MM-yy hh:mm:ss'),'THANKS FOR INVITING',1);
**/
